### ISSUE TITLE
Problema de version de openpyxl

### ISSUE THREAD

**Issue by horazero** [datosgobar/series-tiempo-ar-scraping#37]
Actualmente, respetando las instrucciones de instalación, al ejecutar "make all" el script falla porque la clase InsufficientCoordinatesException no esta declarada. En efecto, la clase no esta declarada en la versión 2.5 de openpyxl en el archivo donde se esperaría que este:
series-tiempo-ar-scraping/lib/python2.7/site-packages/openpyxl/utils/exceptions.py

Si en su lugar se instala la version 2.4, el script corre con normalidad.

**Comment by abenassi** [comment]
Hola @horazero ya sacamos el InsufficientCoordinatesException de la lista de excepciones en un módulo que lo solicitaba, ahora debería andar OK.
